version: '3.8'

networks:
  docker_default:
    external: true

services:
  app:
    container_name: dify-tools
    image: dify-tools
    ports:
      - "8100:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - docker_default